debug: false
spring:
 profiles:
  active: test
---
#开发环境配置
spring:
 profiles: dev
server:
 port: 8080
---
#测试环境配置
spring:
 profiles: test
server:
 port: 9090
---
#生产环境配置
spring:
 profiles: pro
server:
 port: 8082